#!/usr/bin/env python3
"""Build self-contained LaTeX and CSV inventories for the graph-study SI."""

from __future__ import annotations

import csv
import json
from collections import defaultdict
from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT / "paper"
EXPERIMENT = ROOT / "experiments" / "graph-topology-rigorous-2026-07-17"
REPLICATION = (
    ROOT
    / "experiments"
    / "late-physics-representation-replication-2026-07-17"
)


def latex(value: object) -> str:
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(character, character) for character in text)


def variant_label(value: str) -> str:
    return {
        "anchor": "anchor",
        "physics_paraphrase": "physical paraphrase",
        "lexical_counterfactual": "lexical counterfactual",
    }[value]


def build_prompt_inventory(prompts: list[dict[str, object]]) -> None:
    families: dict[str, list[dict[str, object]]] = defaultdict(list)
    family_names: dict[str, str] = {}
    for prompt in prompts:
        family = str(prompt["family_id"])
        families[family].append(prompt)
        family_names[family] = str(prompt["family_name"])

    lines = [
        "% Generated by scripts/build_graph_si_inventory.py.",
        "% Do not edit manually; regenerate from the frozen prompt manifest.",
    ]
    for family in sorted(families):
        lines.extend(
            [
                "",
                rf"\subsubsection*{{{latex(family_names[family])}}}",
            ]
        )
        by_case: dict[str, list[dict[str, object]]] = defaultdict(list)
        for prompt in families[family]:
            by_case[str(prompt["case_id"])].append(prompt)
        for case in sorted(by_case):
            lines.append(rf"\paragraph{{Material case: \texttt{{{latex(case)}}}.}}")
            for prompt in sorted(
                by_case[case],
                key=lambda row: (
                    "anchor",
                    "physics_paraphrase",
                    "lexical_counterfactual",
                ).index(str(row["variant"])),
            ):
                lines.extend(
                    [
                        r"\begin{quote}\small",
                        rf"\textbf{{Prompt ID:}} \path{{{prompt['prompt_id']}}}.\\",
                        (
                            rf"\textbf{{{latex(variant_label(str(prompt['variant'])))}}}; "
                            rf"numeric direction: \texttt{{{latex(prompt['numeric_direction'])}}}; "
                            rf"expected answer: \texttt{{{latex(prompt['expected_outcome'])}}}; "
                            rf"answer order: \texttt{{{latex(prompt['presentation_order'])}}}."
                        ),
                        "",
                        rf"\emph{{{latex(prompt['user'])}}}",
                        r"\end{quote}",
                    ]
                )
    (PAPER / "graph_prompt_inventory.tex").write_text(
        "\n".join(lines) + "\n",
        encoding="utf-8",
    )


def build_edge_inventory(
    prompts: list[dict[str, object]],
    edge_rows: list[dict[str, str]],
    rank_rows: list[dict[str, str]],
) -> None:
    ranks = {
        (int(row["source_index"]), row["target_variant"]): row
        for row in rank_rows
        if row["method"] == "jacobian_band"
    }
    primary = [
        row for row in edge_rows if row["method"] == "jacobian_band"
    ]
    by_family: dict[str, list[dict[str, str]]] = defaultdict(list)
    mapped_csv = []
    for row in primary:
        source_index = int(row["source_index"])
        target_index = int(row["target_index"])
        rank = ranks[(source_index, row["target_variant"])]
        source = prompts[source_index]
        target = prompts[target_index]
        enriched = {
            **row,
            "source_prompt_id": str(source["prompt_id"]),
            "source_case_id": str(source["case_id"]),
            "target_prompt_id": str(target["prompt_id"]),
            "target_case_id": str(target["case_id"]),
            "first_same_outcome_rank": rank["first_positive_rank"],
            "pairwise_auc": rank["pairwise_auc"],
        }
        mapped_csv.append(enriched)
        by_family[row["family"]].append(enriched)

    output_csv = PAPER / "graph_data" / "primary_jacobian_edges_with_ids.csv"
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    with output_csv.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(mapped_csv[0]))
        writer.writeheader()
        writer.writerows(mapped_csv)

    family_names = {
        str(prompt["family_id"]): str(prompt["family_name"])
        for prompt in prompts
    }
    lines = [
        "% Generated by scripts/build_graph_si_inventory.py.",
        "% Complete 144-edge primary frozen-band Jacobian inventory.",
    ]
    for family in sorted(by_family):
        lines.extend(
            [
                "",
                rf"\subsubsection*{{{latex(family_names[family])}}}",
                r"\begingroup\scriptsize",
                r"\begin{longtable}{>{\raggedright\arraybackslash}p{0.19\linewidth}>{\raggedright\arraybackslash}p{0.14\linewidth}>{\raggedright\arraybackslash}p{0.19\linewidth}rrrr}",
                r"\toprule",
                r"Source case / variant & Target variant & Selected target case & Correct & First valid rank & Pair AUC & Cosine \\",
                r"\midrule",
                r"\endhead",
            ]
        )
        for row in sorted(
            by_family[family],
            key=lambda item: (
                item["source_case_id"],
                item["source_variant"],
                item["target_variant"],
            ),
        ):
            source_short = (
                rf"\texttt{{{latex(row['source_case_id'])}}} / "
                rf"{latex(variant_label(row['source_variant']))}"
            )
            lines.append(
                " & ".join(
                    [
                        source_short,
                        latex(variant_label(row["target_variant"])),
                        rf"\texttt{{{latex(row['target_case_id'])}}}",
                        "yes" if row["same_outcome"] == "True" else "no",
                        latex(row["first_same_outcome_rank"]),
                        f"{float(row['pairwise_auc']):.2f}",
                        f"{float(row['cosine']):.4f}",
                    ]
                )
                + r" \\"
            )
        lines.extend(
            [
                r"\bottomrule",
                r"\end{longtable}",
                r"\endgroup",
            ]
        )
    (PAPER / "graph_primary_edge_inventory.tex").write_text(
        "\n".join(lines) + "\n",
        encoding="utf-8",
    )


def main() -> None:
    manifest = json.loads(
        (REPLICATION / "prompt_manifest.json").read_text(encoding="utf-8")
    )
    prompt_by_id = {
        str(prompt["prompt_id"]): prompt for prompt in manifest["prompts"]
    }
    with np.load(REPLICATION / "representations.npz", allow_pickle=False) as data:
        prompt_ids = data["prompt_ids"].astype(str).tolist()
    prompts = [prompt_by_id[prompt_id] for prompt_id in prompt_ids]

    with (EXPERIMENT / "replication_relation_graph_selected_edges.csv").open(
        newline="",
        encoding="utf-8",
    ) as handle:
        edge_rows = list(csv.DictReader(handle))
    with (EXPERIMENT / "replication_relation_candidate_ranks.csv").open(
        newline="",
        encoding="utf-8",
    ) as handle:
        rank_rows = list(csv.DictReader(handle))

    build_prompt_inventory(prompts)
    build_edge_inventory(prompts, edge_rows, rank_rows)
    print(
        json.dumps(
            {
                "prompts": len(prompts),
                "primary_edges": sum(
                    row["method"] == "jacobian_band" for row in edge_rows
                ),
                "prompt_inventory": "paper/graph_prompt_inventory.tex",
                "edge_inventory": "paper/graph_primary_edge_inventory.tex",
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
