#!/usr/bin/env python3
"""Build the LaTeX SI inventory for the graph-identifiability audit."""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
EXP = ROOT / "experiments" / "graph-isomorphism-generalization-2026-07-18"
OUT = ROOT / "paper" / "graph_generalization_audit.tex"

FAMILY_ORDER = [
    "crosslink-density-modulus",
    "dislocation-density-strength",
    "obstacle-spacing-orowan",
    "particle-fraction-modulus",
    "pearlite-spacing-strength",
    "porosity-modulus",
]
FAMILY_LABELS = {
    "crosslink-density-modulus": "Crosslink density--rubbery modulus",
    "dislocation-density-strength": "Dislocation density--flow strength",
    "obstacle-spacing-orowan": "Obstacle spacing--Orowan stress",
    "particle-fraction-modulus": "Stiff-particle fraction--modulus",
    "pearlite-spacing-strength": "Pearlite spacing--yield strength",
    "porosity-modulus": "Porosity--elastic modulus",
}
ORIENTATION = {
    "crosslink-density-modulus": ("direct", "$+1$"),
    "dislocation-density-strength": ("direct", "$+1$"),
    "obstacle-spacing-orowan": ("inverse", "$-1$"),
    "particle-fraction-modulus": ("direct", "$+1$"),
    "pearlite-spacing-strength": ("inverse", "$-1$"),
    "porosity-modulus": ("inverse", "$-1$"),
}


def metric(frame: pd.DataFrame, configuration: str, family: str) -> float:
    row = frame[
        (frame["configuration"] == configuration)
        & (frame["heldout_family"] == family)
    ]
    if len(row) != 1:
        raise RuntimeError(
            f"expected one row for {configuration=} and {family=}, found {len(row)}"
        )
    return float(row.iloc[0]["auc"])


def main() -> None:
    validation = json.loads((EXP / "VALIDATION.json").read_text())
    mapping = pd.read_csv(EXP / "mapping_method_summary.csv").set_index("method")
    absolute = pd.read_csv(EXP / "gin_family_metrics.csv")
    relation = pd.read_csv(EXP / "relation_gin_family_metrics.csv")
    density = pd.read_csv(EXP / "spectral_density_ablations.csv")
    exact = json.loads((EXP / "study6_partition_statistics.json").read_text())

    lines = [
        "% Generated by scripts/build_graph_generalization_si.py.",
        "% Do not edit manually; regenerate from the archived audit outputs.",
        "",
        "\\subsection*{Audit scope and exact identifiability}",
        "",
        "These analyses add no new scientific prompts and require no new Gemma "
        "forward pass. They reuse the 72 exact natural questions printed in "
        "Section S4C, their 25 archived layer states, and the same three frozen "
        "Jacobian lenses. The prompt manifest contains six supplied mechanism "
        "families, four material cases per family, and three surface variants "
        "per case. All 72 prompts, all layers, all methods, all random seeds, "
        "and all failed gates were retained.",
        "",
        "For prompt node $i$ in mechanism $f$, let $x_{fi}=+1$ for a stated "
        "numerical increase and $-1$ for a decrease; let $s_f=+1$ for a direct "
        "input--property law and $-1$ for an inverse law; and let $y_{fi}=+1$ "
        "or $-1$ denote the registered physical-property outcome. The frozen "
        "manifest satisfies exactly",
        "\\begin{equation}",
        "y_{fi}=s_f x_{fi}",
        "\\end{equation}",
        "for every one of the 72 prompts. Therefore, within one mechanism,",
        "\\begin{equation}",
        "y_{fi}y_{fj}=(s_fx_{fi})(s_fx_{fj})=x_{fi}x_{fj}.",
        "\\end{equation}",
        "Thus ``same versus different physical outcome'' is exactly the same "
        "binary relation as ``same versus different numerical direction'' "
        "inside each supplied family. An unlabeled family graph can identify "
        "at most the two-way equivalence class $\\{y_f,-y_f\\}$; it cannot assign "
        "an absolute physical sign without the mechanism orientation $s_f$. "
        "This is a proof about benchmark identifiability, not a claim that "
        "Gemma contains no physical information.",
        "",
        "\\begin{table}[H]",
        "\\centering",
        "\\small",
        "\\caption{Mechanism orientation in the 72-prompt audit. The physical "
        "label is generated exactly by $y=sx$.}",
        "\\begin{tabular}{lll}",
        "\\toprule",
        "Mechanism & Response orientation & $s_f$ \\\\",
        "\\midrule",
    ]
    for family in FAMILY_ORDER:
        orientation, sign = ORIENTATION[family]
        lines.append(
            f"{FAMILY_LABELS[family]} & {orientation} & {sign} \\\\"
        )
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
            "\\subsection*{Label-blind graph matching and isomorphism}",
            "",
            "For every unordered mechanism pair, all 24 bijections between the "
            "four material cases were scored using anchor--paraphrase "
            "similarities only. The best map was frozen before evaluating "
            "counterfactual similarities or revealing the physical labels. "
            "Held-out similarity form transferred strongly for all 15 pairs: "
            f"mean correlation {mapping.loc['jacobian', 'heldout_topology_mean']:.3f} "
            "for Jacobian states, "
            f"{mapping.loc['direct', 'heldout_topology_mean']:.3f} for direct "
            "decoder-basis states, and "
            f"{mapping.loc['raw', 'heldout_topology_mean']:.3f} for raw states. "
            "All 15 correlations were positive for each representation. "
            "However, Jacobian physical case agreement was "
            f"{mapping.loc['jacobian', 'physical_agreement']:.3f} "
            f"(structured-null $p={mapping.loc['jacobian', 'physical_structured_null_p']:.3f}$). "
            "No mechanism pair was exactly isomorphic under the surface-variant "
            "labels. Weisfeiler--Lehman similarity exceeded its constrained "
            "null nominally ($p=0.0123$) but not after the seven-test "
            "Benjamini--Hochberg correction ($q=0.0861$). The transferable "
            "object is therefore graded similarity form, not a reliable "
            "physical case map or a Jacobian-specific graph.",
            "",
            "\\subsection*{Whole-mechanism graph learning}",
            "",
            "A three-block graph isomorphism network (GIN) was trained on four "
            "mechanisms, selected on a fifth, and tested on the completely "
            "unseen sixth. Twenty seeds were run for every configuration. The "
            "absolute-polarity node input contained a constant, surface-variant "
            "one-hot, the explicitly supplied numerical direction, normalized "
            "depth, in/out degree, and edge strengths; it excluded prompt text, "
            "material identity, mechanism identity, answer words, and physical "
            "labels. A matched graphless multilayer perceptron and constrained "
            "edge shuffle served as controls. The numerical-direction "
            "configuration predicts a deliberately supplied input and is "
            "therefore a positive-control readback rather than a graph-discovery "
            "endpoint. The separate relation GIN excludes numerical direction "
            "and surface variant. It evaluates all 72 eligible ordered pairs "
            "within each 12-node family graph, requiring different material "
            "cases and different surface variants. Thus its near-chance result "
            "does not contradict the perfect readback of a feature explicitly "
            "given to the absolute model. The node-permutation audit reproduced "
            "every reported AUC exactly.",
            "",
            "\\begin{table}[H]",
            "\\centering",
            "\\scriptsize",
            "\\caption{Whole-mechanism-held-out graph learning. The numerical-"
            "direction column is an input-readback positive control because "
            "that feature was supplied to the absolute-label network. Even "
            "with direction supplied, absolute physical polarity does not "
            "generalize; the separate polarity-free relation network also "
            "fails. ROC--AUC 0.5 denotes no ordering information.}",
            "\\begin{tabular}{lrrr}",
            "\\toprule",
            "Held-out mechanism & Physical polarity & Direction input readback & Same/different relation \\\\",
            "\\midrule",
        ]
    )
    for family in FAMILY_ORDER:
        physical = metric(absolute, "topology_gin_physical", family)
        numeric = metric(absolute, "topology_gin_numeric", family)
        relational = metric(
            relation, "relation_jacobian_gin_physical", family
        )
        lines.append(
            f"{FAMILY_LABELS[family]} & {physical:.3f} & {numeric:.3f} & "
            f"{relational:.3f} \\\\"
        )
    physical_mean = absolute[
        absolute["configuration"] == "topology_gin_physical"
    ]["auc"].mean()
    numeric_mean = absolute[
        absolute["configuration"] == "topology_gin_numeric"
    ]["auc"].mean()
    relation_mean = relation[
        relation["configuration"] == "relation_jacobian_gin_physical"
    ]["auc"].mean()
    lines.extend(
        [
            "\\midrule",
            f"Six-mechanism mean & {physical_mean:.3f} & {numeric_mean:.3f} & "
            f"{relation_mean:.3f} \\\\",
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
            "Absolute physical AUC exceeded 0.5 for only one of six held-out "
            "mechanisms; the polarity-free relation GIN exceeded 0.5 for only "
            "two. The supplied numerical-direction feature was read back at "
            "AUC 1.000 in every family, as expected for this positive control. "
            "This value is not evidence that topology discovered direction. "
            "Below-chance physical AUC is expected when an otherwise "
            "coherent two-way partition receives the wrong absolute sign in a "
            "held-out mechanism; it is not evidence that the network learned "
            "an anti-physical law.",
            "",
            "\\subsection*{Spectral communities and graph density}",
            "",
            "A label-blind normalized-Laplacian partition was calibrated on "
            "1,000 positive and 1,000 negative synthetic graphs. Mean adjusted "
            "Rand index (ARI) was 0.987 for positive block graphs and 0.044 for "
            "negative controls; ordinary signed accuracy after random "
            "graph-wide flips was 0.496. ARI is invariant to swapping the two "
            "community names: 1 is perfect agreement, and values near 0 are "
            "random-like.",
            "",
            "\\begin{table}[H]",
            "\\centering",
            "\\small",
            "\\caption{Community agreement as progressively more graded "
            "similarity information is retained. The smallest corrected "
            "$q$-value over the 12 secondary representation-by-density tests "
            "is 0.092.}",
            "\\begin{tabular}{lrrr}",
            "\\toprule",
            "Retained graph & Jacobian & Direct & Raw \\\\",
            "\\midrule",
        ]
    )
    mode_labels = {
        "binary_top1": "Top-one binary",
        "weighted_top1": "Top-one weighted",
        "weighted_top2": "Top-two weighted",
        "weighted_complete_candidates": "All candidate weights",
    }
    for mode, label in mode_labels.items():
        values = {
            method: float(
                density[
                    (density["method"] == method) & (density["mode"] == mode)
                ].iloc[0]["mean_ari"]
            )
            for method in ("jacobian", "direct", "raw")
        }
        lines.append(
            f"{label} & {values['jacobian']:.3f} & {values['direct']:.3f} & "
            f"{values['raw']:.3f} \\\\"
        )
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
            "The registered sparse top-one graph retains only modest "
            "community information. Agreement increases when all eligible "
            "similarities are retained, but direct states match the Jacobian "
            "result and raw states are stronger. Hard edge selection therefore "
            "discards graded relational organization; the result does not "
            "establish a uniquely Jacobian physical community.",
            "",
            "\\subsection*{Exhaustive balanced partitions}",
            "",
            "To avoid dependence on one community algorithm, every one of the "
            "462 unique balanced six-versus-six partitions of each 12-node "
            "family graph was evaluated. A second endpoint fitted all 35 "
            "balanced four-versus-four partitions using anchors and "
            "paraphrases only, then assigned the four held-out "
            "counterfactuals. The stronger blockwise null preserved every "
            "ordered surface-variant block and its weight distribution.",
            "",
            "\\begin{table}[H]",
            "\\centering",
            "\\small",
            "\\caption{Exhaustive partition results. Values are six-family "
            "mean ARI; $p$ is the exact blockwise-null probability.}",
            "\\begin{tabular}{lrr}",
            "\\toprule",
            "Representation & Full 12-node graph & Counterfactual held out \\\\",
            "\\midrule",
        ]
    )
    for method in ("jacobian", "direct", "raw"):
        complete = exact["summary"][method]["complete"]
        heldout = exact["summary"][method]["heldout_surface"]
        lines.append(
            f"{method.capitalize()} & {complete['mean_ari']:.3f} "
            f"($p={complete['null_exact_p']:.3f}$) & "
            f"{heldout['mean_ari']:.3f} "
            f"($p={heldout['null_exact_p']:.3f}$) \\\\"
        )
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
            "",
            "The registered relation is not the uniquely dominant balanced "
            "division of the weighted graph in this cohort, and a partition "
            "fitted without counterfactuals does not transfer to that held-out "
            "phrasing. Spectral and exhaustive results need not coincide because "
            "they optimize different graph objectives; their combination shows "
            "that the conclusion depends on how a community is defined. These "
            "are not proofs of absence across a larger materials population: "
            "six mechanisms provide limited power, and the near-threshold "
            "$q=0.092$ density result and $p=0.087$ complete-partition result "
            "leave open moderate effects in a larger prospective cohort.",
            "",
            "\\subsection*{Complete run inventory and reproduction}",
            "",
            f"The independent validator reports {validation['prompt_count']} prompts, "
            f"{validation['layer_count']} layers, "
            f"{validation['mechanism_count']} mechanisms, "
            f"{validation['absolute_gin_runs']:,} absolute-GIN runs, and "
            f"{validation['relation_gin_runs']:,} relation-GIN runs. The "
            "option-free representation array has SHA-256 "
            f"\\texttt{{{validation['sha256']['experiments/option-free-question-end-2026-07-18/representations.npz']}}}; "
            "the exact prompt manifest has SHA-256 "
            f"\\texttt{{{validation['sha256']['experiments/late-physics-representation-replication-2026-07-17/prompt_manifest.json']}}}. "
            "The complete pair maps, GIN logits, seed rows, spectral partitions, "
            "density ablations, exact partitions, null arrays, protocols, "
            "environment versions, and validation record are retained under "
            "\\path{experiments/graph-isomorphism-generalization-2026-07-18/}.",
            "",
            "\\begin{verbatim}",
            "python scripts/analyze_graph_isomorphism_generalization.py",
            "python scripts/run_graph_isomorphism_gin.py",
            "python scripts/analyze_graph_gauge_generalization.py",
            "python scripts/run_graph_relation_gin.py",
            "python scripts/analyze_spectral_graph_communities.py",
            "python scripts/analyze_exact_graph_partitions.py",
            "python scripts/plot_graph_generalization_audit.py",
            "python scripts/validate_graph_generalization_audit.py",
            "python scripts/build_graph_generalization_si.py",
            "\\end{verbatim}",
            "",
            "These commands analyze archived states; they do not invoke Gemma "
            "or create additional scientific prompts. The 72 natural questions "
            "are printed once in Section S4C rather than duplicated here.",
            "",
        ]
    )

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
