#!/usr/bin/env python3
"""Build the manuscript's broad and prospective steering-prompt inventory."""

from __future__ import annotations

import json
import csv
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "paper/steering_prompt_inventory.tex"
V3_RESULTS_OUT = ROOT / "paper/steering_v3_result_table.tex"
V4_RESULTS_OUT = ROOT / "paper/steering_v4_result_table.tex"

FAMILY_LABELS = {
    "intergranular-corrosion": "Intergranular corrosion",
    "martensitic-transformation": "Martensitic transformation",
    "grain-size-strengthening": "Grain-size strengthening",
}


def tex(value: object) -> str:
    text = str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in text)


def load(name: str) -> dict:
    return json.loads((ROOT / name).read_text())


def prompt_table(rows: list[dict]) -> list[str]:
    grouped: dict[tuple[str, str], list[dict]] = defaultdict(list)
    order: list[tuple[str, str]] = []
    for row in rows:
        key = (row["family_id"], row["condition_id"])
        if key not in grouped:
            order.append(key)
        grouped[key].append(row)

    lines = [
        r"\begin{longtable}{>{\raggedright\arraybackslash}p{0.20\linewidth}>{\raggedright\arraybackslash}p{0.74\linewidth}}",
        r"\toprule",
        r"Condition and frozen answer & Exact rendered prompts and clean choices \\",
        r"\midrule",
        r"\endhead",
    ]
    current_family = None
    for family_id, condition_id in order:
        family_rows = grouped[(family_id, condition_id)]
        if family_id != current_family:
            lines.extend([
                rf"\multicolumn{{2}}{{l}}{{\textbf{{{tex(FAMILY_LABELS[family_id])}}}}} \\",
                r"\addlinespace[2pt]",
            ])
            current_family = family_id
        expected = family_rows[0].get("expected_outcome")
        expected_text = tex(expected) if expected is not None else "none (near-threshold)"
        regime = tex(family_rows[0].get("regime", "not applicable"))
        breakable_condition_id = tex(condition_id).replace("-", r"-\allowbreak{}")
        left = (
            rf"\texttt{{{breakable_condition_id}}}\newline "
            rf"Regime: {regime}\newline Frozen answer: \texttt{{{expected_text}}}"
        )
        rendered = []
        for row in family_rows:
            clean = row["clean"]
            clean_choice = tex(clean["choice"])
            correctness = row.get("clean_expected_correct")
            if correctness is None:
                status = "not scored"
            else:
                status = "correct" if correctness else "incorrect"
            rendered.append(
                rf"\textbf{{{tex(row['presentation_order'])}.}} ``{tex(row['user'])}'' "
                rf"Clean choice: \texttt{{{clean_choice}}} ({status})."
            )
        right = r"\newline\smallskip ".join(rendered)
        lines.extend([rf"{left} & {right} \\", r"\addlinespace[4pt]"])
    lines.extend([r"\bottomrule", r"\end{longtable}"])
    return lines


def main() -> None:
    v3_manifest = load("experiments/semantic-steering-v3-preregistration.json")
    v3_raw = load("experiments/semantic-steering-v3_raw.json")
    v4_raw = load("experiments/relational-grain-steering-v4_raw.json")

    lines = [
        "% Generated by scripts/build_steering_prompt_inventory_tex.py.",
        "% Do not edit manually; regenerate from the frozen manifests and raw preflight rows.",
        r"\begingroup",
        r"\small",
        r"\setlength{\LTpre}{0.25em}",
        r"\setlength{\LTpost}{0.45em}",
        r"\sloppy",
        r"\subsection*{S7.1 Frozen direction-fitting prompts}",
        "Each sentence below was run independently. Its final-prompt state contributed one unit gradient; the three gradients within a family were averaged and renormalized. The outcome answer words were excluded.",
    ]
    for family in v3_manifest["families"]:
        positive = ", ".join(rf"\texttt{{{tex(word)}}}" for word in family["concept_positive"])
        negative = ", ".join(rf"\texttt{{{tex(word)}}}" for word in family["concept_negative"])
        lines.append(rf"\paragraph{{{tex(FAMILY_LABELS[family['family_id']])}.}} Positive ensemble: {positive}. Negative ensemble: {negative}.")
        lines.append(r"\begin{enumerate}")
        for prompt in family["direction_fit_prompts"]:
            lines.append(rf"\item ``{tex(prompt)}''")
        lines.append(r"\end{enumerate}")

    lines.extend([
        r"\clearpage",
        r"\subsection*{S7.2 Broad mechanism-steering prompts}",
        "These are all 60 exact model inputs: 30 physical conditions, each shown in both ordered-answer forms. The table also records the clean choice before intervention. Near-threshold cases deliberately have no frozen correct answer.",
        *prompt_table(v3_raw["preflight"]),
        r"\clearpage",
        r"\subsection*{S7.3 Prospective relational matched-pair prompts}",
        "These are all 24 exact model inputs frozen for the prospective relation-reversal test. The confirmation reused the broad screen's direction-fitting prompts without alteration.",
        *prompt_table(v4_raw["preflight"]),
        r"\endgroup",
        "",
    ])
    OUT.write_text("\n".join(lines))
    print(OUT.relative_to(ROOT))

    with (ROOT / "experiments/semantic-steering-v3_condition_effects.csv").open() as handle:
        v3_conditions = list(csv.DictReader(handle))
    with (ROOT / "experiments/relational-grain-steering-v4_condition_effects.csv").open() as handle:
        v4_conditions = list(csv.DictReader(handle))

    v3_by_key = {
        (row["target_family_id"], row["condition_id"]): row
        for row in v3_conditions
    }
    v3_result_lines = [
        "% Generated by scripts/build_steering_prompt_inventory_tex.py.",
        "% Do not edit manually; regenerate from the frozen result CSV files.",
        r"\subsection*{S5.1 Every broad-screen physical-condition endpoint}",
        "The matched, wrong-mechanism, direct, and random columns are changes in positive-answer minus negative-answer log odds from the negative to positive dose endpoint. Values are averaged over answer orders and over the registered replicates for each control class.",
        r"\begingroup\scriptsize",
        r"\begin{longtable}{>{\raggedright\arraybackslash}p{0.34\linewidth}lrrrr}",
        r"\toprule",
        r"Physical condition & Regime & Matched J & Wrong & Direct & Random \\",
        r"\midrule",
        r"\endhead",
    ]
    for family in v3_manifest["families"]:
        family_id = family["family_id"]
        v3_result_lines.extend([
            rf"\multicolumn{{6}}{{l}}{{\textbf{{{tex(FAMILY_LABELS[family_id])}}}}} \\",
            r"\addlinespace[2pt]",
        ])
        for prompt in family["confirmation_prompts"]:
            row = v3_by_key[(family_id, prompt["condition_id"])]
            v3_result_lines.extend([
                (
                    rf"\texttt{{{tex(prompt['condition_id'])}}} & {tex(row['regime'])} & "
                    rf"${float(row['own_jacobian']):+.3f}$ & "
                    rf"${float(row['mean_wrong_mechanisms']):+.3f}$ & "
                    rf"${float(row['direct_decoder']):+.3f}$ & "
                    rf"${float(row['random_directions']):+.3f}$ \\"
                ),
                r"\addlinespace[2pt]",
            ])
    v3_result_lines.extend([
        r"\bottomrule",
        r"\end{longtable}",
        r"\endgroup",
        "",
    ])
    V3_RESULTS_OUT.write_text("\n".join(v3_result_lines))
    print(V3_RESULTS_OUT.relative_to(ROOT))

    v4_result_lines = [
        "% Generated by scripts/build_steering_prompt_inventory_tex.py.",
        "% Do not edit manually; regenerate from the frozen result CSV files.",
        r"\subsection*{S6.1 Every prospective matched condition}",
        "Raw matched is the higher-minus-lower endpoint. Expected-aligned reverses the sign for coarsening, so a positive value means movement toward the frozen correct answer. Control columns use the same alignment.",
        r"\begingroup\scriptsize",
        r"\begin{longtable}{>{\raggedright\arraybackslash}p{0.25\linewidth}lrrrrr}",
        r"\toprule",
        r"Material pair & Relation & Raw J & Aligned J & Wrong & Direct & Random \\",
        r"\midrule",
        r"\endhead",
    ]
    for row in v4_conditions:
        v4_result_lines.extend([
            (
                rf"\texttt{{{tex(row['pair_id'])}}} & {tex(row['relation'])} & "
                rf"${float(row['own_jacobian']):+.3f}$ & "
                rf"${float(row['own_expected_aligned']):+.3f}$ & "
                rf"${float(row['wrong_expected_aligned']):+.3f}$ & "
                rf"${float(row['direct_expected_aligned']):+.3f}$ & "
                rf"${float(row['random_expected_aligned']):+.3f}$ \\"
            ),
            r"\addlinespace[2pt]",
        ])
    v4_result_lines.extend([
        r"\bottomrule",
        r"\end{longtable}",
        r"\endgroup",
        "",
    ])
    V4_RESULTS_OUT.write_text("\n".join(v4_result_lines))
    print(V4_RESULTS_OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
